language: php
php:
- '7.0'
sudo: false
before_script:
- travis_retry composer self-update
- travis_retry composer update --no-interaction --prefer-source
- npm install --save-dev
- npm run production
- cp .env.example .env
- php artisan key:generate
before_deploy:
- rm .env
- chmod +x configHeroku.php
- php configHeroku.php
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: ZQLWAF3mz97G7FIZboq03rHi7xDH6W7d9KhIqnG6WFYXNYo966qXQaPEeA5fVTDI+ZpRc0KPOrOV6tguOFTsCX4cc2ZwB/Pt5huHTo/+zWoHT0tEHKgIY11e7iWqZ/f8NRVtqfXW9hBEvYZDkExNMXEYZwO8wTz92MQNvmD8AxqyD9Tmv/bBJFUnGtBxJvfa2Qu+iERGXjxEcMbPR0BvxHfMkxINdM66oGhSwSREW2hRoRbfEvpXTpFgtAWmXgCfmze8d/IewKD04XYBtSE6QubDmZnUHTScJnVz4v272wnPwJGJmpZNblZ9W4cil0ucPuWdkjDsfBmL0XN8CYNKL8e8aMu2yFmcUYRYntWHyxMP2ufVx8dLNmuaT2M9v5Biyy3i9LsXQRvmq5JLQzNms1oq+Vl0giOzQVk14M9hOq8lJvB9Ut7Vjjiixd9CFBLTx2jQp9z2cVpnUXp3ZT0aBxqSFT4zNT2uTiouvMKJREz8JBrq1rZ8ACa9do6mI3FjD3BzLevQR0Z8rgRjrf6JyumNeYwCzrKfi1Kn0mgJ66Cgmn9b42uPELXBs19iAvQ6bCqJEXmRRR6MKL+su0Scma1T6TWfwG6T+samm7z2lH5jEqMBM6u2GuJYqPxSs+LJFJQD7FSttNWwRqmKx74lYczMlbYVr4KV6DMqabmdSt0=
  app: simpletroc
  on:
    branch: master
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/871dd60a0eae29f5bf1f
    on_success: always
    on_failure: always
    on_start: never
