language: php
php:
  - '7.0'
sudo: false

addons:
  ssh_known_hosts: simpletroc.srvz-webapp.he-arc.ch

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source
  - npm install --save-dev
  - cp .env.example .env
  - php artisan key:generate
  - npm run dev
  - openssl aes-256-cbc -K $encrypted_19b535f00b0d_key -iv $encrypted_19b535f00b0d_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -e "ssh -p 2211" --delete-after --quiet $TRAVIS_BUILD_DIR poweruser@simpletroc.srvz-webapp.he-arc.ch:www/app/SimpleTroc
  on:
    branch: master
