language: php
php:
- '7.0'
sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source
  - npm install --save-dev
  - cp .env.example .env
  - php artisan key:generate #shitty but needed for phpunit

before_deploy:
    - rm .env
    - "chmod +x configHeroku.php"
    - "php configHeroku.php"

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: NpWKQ5stENvdHXkFqno07r7rw1kXWdJGWkzq8CVWNU+mLrSx8iQTx1B/SkX2qrUsNVtcElC1hMypWvz/ZSQNL4ytQ6eXkshqoxg6Pd3l1zGEe2v9YjyhB87fdyv2lWoItnzk0aUYBK8+WOsnn72xluPN3HZK+6u/dPM11VlTTsiCu6e8Nth0kYIuKPrlkWy1Ioz7kKXa+SSUjYc88YMIzlqpRHUHrW/4yyrjLgTHQxWZL3jfOVG4J+eU/PuDPLQwySKW/GaGaqG06fMu6p+sISjTAqi9MnRmPgfSWX/WAnYW2OmhKXEA15PGQzQZP/pbP8a0AZJZCvM9FWvRsJz/GotKYez3JJtYwux+Kfsp4k5ToCC+f9fzWu+xGeSssUrGyC1Um52gWqT+PweUYlx9NkNczR3JOqKVvxdRVf5TE427DMClJQY8TXirtoi+9uwxR7aXx4dPPTZL7WXc7Fu3YFzrvljpSQiX2tNo72d6uFaD9uTvaSbS3nQvI7Teji7a5qEkHKfY/zWm0G2nfcEs6jxayXzMbzDoJ3q6nQaMTR7KWHIykBAsXXxFT0V/Bq6bCDuKfh4Bk9P9nJaTcpvyCMF3bSvBYPmCCH1foTeBwsgm64/qmq8BvLO416fZHoIyU+K6nmftq3tyPuBKUwVKGD92B8B/6vF4tfyBrbXlv/0=
  app: simpletroc
  on:
    branch: master
  run:
    - "composer self-update"
    - "composer install --no-interaction"
    - "npm install"
    - "npm run production"
    - "php artisan migrate"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/871dd60a0eae29f5bf1f
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
